### ISSUE TITLE
Why not `.reduce`?

### ISSUE THREAD

**Issue by pitaj** [Ginden/set-methods#3]
There may be few use cases for reduce on a set, but they do exist. It would serve as extra consistency with Arrays as well.

**Comment by domenic** [comment]
reduce() is currently included. However, it's a bit strange as it assumes an ordering, which JS sets have, but is not part of the usual concept of a set.

reduceRight() is missing though. I think either neither or both should be included.

**Comment by pitaj** [comment]
In my opinion, not having reduce makes more sense, as there's no way to sort a set. As you said, sets don't normally have an order. 

I think doing `[...set].reduce()` is preferable to having `reduce` on sets.

**Comment by Ginden** [comment]
I understand your concerns about `reduce` ordering. I had them too, but since then I was convinced that it totally makes sense to fold (reduce) set, because all iterating methods depend on some implicit "ordering". It should be treated as implementation detail. First element iterated isn't "first element in set" - it's "first element to be iterated over". 

Personally I would like to make set iteration implementation-dependent but guaranteed to be stable.

**Comment by domenic** [comment]
OK, so why doesn't indexOf(el) exist then? It would what position in iteration order the element appears.

**Comment by Ginden** [comment]
Because sets aren't indexable, so it would be virtually useless (though, Python provide generic `enumerate` method anyway). Position in iteration order is "virtual" - it can change anytime (eg. calling `.delete` method will move other items positions).

Conceptually, position in iteration order shouldn't even matter. And there are many use cases where starting item for `.reduce` doesn't matter, especially when performed operation is associative (summation is simplest example).

**Comment by domenic** [comment]
I don't find the comparison convincing. Calling `.splice()` will move other items' positions in an array.

If position in iteration order shouldn't matter, then please don't add reduce(), as it's entirely built on that idea. It would indeed be a different story if we had a language with some way to enforce associative-only operations, but we don't, so iteration order is an intrinsic part of the reduce method.

**Comment by pitaj** [comment]
It's also worth mentioning that for most associative operations, like `sum` and `product`, it's probably better to have `Math` functions for those specific operations. For instance, `Math.sum(...numbers)` and `Math.product(...numbers)`

**Comment by tabatkins** [comment]
> If position in iteration order shouldn't matter, then please don't add reduce(), as it's entirely built on that idea. 

Strongly disagree. As you note in the following (unquoted) sentence, reduce() on a set completely makes sense if you have commutative+associative reducers, but in reality sets are ordered on the web platform (note that Infra only defines [ordered sets](https://infra.spec.whatwg.org/#sets) for exactly this reason), and so arbitrary reducers make sense just fine.

I do agree that `reduceRight()` should exist, simply for symmetry.  Weird to be able to reduce from one direction but not the other, just because the "normal" direction *implies* its direction (left) rather than putting it into the name.

I'm ambivalent on `.indexOf()` - it does have a meaningful definition, but it's *useless*.

**Comment by pitaj** [comment]
We need to decide if the _implicit_ insertion-ordering of Set qualifies as Array-like ordered behavior. If it does, then `reduce`, `indexOf`, etc make sense (maybe even `sort` if it returns a new Set). Otherwise, they should not be included on Set, instead certain analogues by different names can be added (like `fold` instead of `reduce`).

**Comment by Ginden** [comment]
This issue was moved to Ginden/collection-methods#3
